### ISSUE TITLE
socat[2094] E openssl-method="SSLv3": method unknown or not provided by library

### ISSUE THREAD

**Issue by Teymoor-Ali** [thomaspatzke/POODLEAttack#3]
I get the error socat[2094] E openssl-method="SSLv3": method unknown or not provided by library when running ./poodle-dev.sh sslserver OR socat -v -x OPENSSL-LISTEN:4433,verify=0,method=SSLv3,cert=cert-poodle.pem,key=key-poodle.pem,reuseaddr,fork TCP:localhost:4080 . Im using Kali linux(latest version) to test this.

**Comment by Teymoor-Ali** [comment]
Im going to try installing an older version of socat, which one did you use?

EDIT: tried it and got new error called: unknown device/address "OPENSSL-LISTEN"

**Comment by thomaspatzke** [comment]
I think the used OpenSSL library doesn't supports SSLv3 anymore. You should rebuild OpenSSL with SSLv3 support and then build socat against it.

**Comment by Teymoor-Ali** [comment]
Would just installing a older version of openssl and Socat? tried them but got the same error in the last comment from them.  How do i link socat with OpenSSL?

**Comment by thomaspatzke** [comment]
Socat tries by default to identify the OpenSSL library + headers on your system and then builds against it. In your specific case you have to build a version of OpenSSL that supports SSLv3 (current with appropriate options or an older one) and then provide it to the build process of socat. This is [described in the bottom of the install section of socat](http://www.dest-unreach.org/socat/doc/README).
